//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


   public partial class Default
   {

      /// <summary>
      /// me control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Label me;

      /// <summary>
      /// Master property.
      /// </summary>
      /// <remarks>
      /// Auto-generated property.
      /// </remarks>
      public new WebApplication1.Master_Pages.Default Master
      {
         get
         {
            return ((WebApplication1.Master_Pages.Default)(base.Master));
         }
      }
   }
}
